import Intro from '@/components/Intro'
import NavBar from '@/components/NavBar'
import Head from 'next/head'
import { useDispatch } from 'react-redux'
import { setUserToken, setUserData } from '@/Utils/UserSlice'
import { useEffect } from 'react'
import Cookies from 'js-cookie'
import { toast } from 'react-toastify'
import useSWR from 'swr'
import { get_job, get_linkedin_job} from '@/Services/job'
import { setJobData } from '@/Utils/JobSlice'
import { InfinitySpin } from 'react-loader-spinner'
export default function Home() {
  const dispatch = useDispatch();
  const token = Cookies.get('token');

  

  const { data: jobData, error: er1, isLoading: load1 } = useSWR('api/db1/getAllJobs', get_job);


  const {data: LinkedInJobData , error: er2 , isLoading: load2} = useSWR('api/db2/getAllLinkedInJobs', get_linkedin_job)

  console.log('data', jobData);
  console.log(LinkedInJobData);

  jobData = [...jobData?.data, ...LinkedInJobData?.data]

  useEffect(() => {
    if (jobData) dispatch(setJobData(jobData?.data))
  }, [jobData, dispatch])


  useEffect(() => {
    if (token) {
      dispatch(setUserToken(token))
    }
    else {
      localStorage.removeItem('user')
      dispatch(setUserData(null))
    }
  }, [token, dispatch])

  return (
    <>

      <Head>
        <title>Job Poral</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Search and apply for the latest jobs in your field. Explore opportunities from top companies and make your career dreams come true." />
        <meta name="keywords" content="job portal, job search, career opportunities, employment, job listings, job openings, job vacancies, job postings, hiring, recruitment" />
        <meta name="robots" content="index, follow" />
        <link rel="canonical" href="https://job-portal-teal.vercel.app/" />
        <meta name="author" content="GM-SHUVO" />
        <meta property="og:title" content="Find Your Dream Job | Job Portal Name" />
        <meta name="twitter:title" content="Find Your Dream Job | Job Portal Name" />
        <meta name="language" content="en-US" />
        

      </Head>

      {
        load1 || load2 ? (
          <div className='bg-gray w-full h-screen flex items-center flex-col justify-center'>
            <InfinitySpin width='200' color="#4f46e5" />
            <p className='text-xs uppercase'>Loading Resources Hold Tight...</p>
          </div>
        ) : (
          <>
            <NavBar />
            <div className="w-full h-screen bg-gray-200  text-black">
              <Intro />
            </div>
          </>
        )
      }
    </>
  )
}